-- Bookmark Manager Database Schema (Postgres)
-- Run this in the Supabase SQL editor.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);

CREATE TABLE IF NOT EXISTS collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    parent_id BIGINT NULL REFERENCES collections(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_collections_user_id ON collections (user_id);
CREATE INDEX IF NOT EXISTS idx_collections_parent_id ON collections (parent_id);

CREATE TABLE IF NOT EXISTS bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    collection_id BIGINT NULL REFERENCES collections(id) ON DELETE SET NULL,
    title VARCHAR(255) NOT NULL,
    url TEXT NULL,
    type TEXT NOT NULL DEFAULT 'link',
    content TEXT NULL,
    description TEXT NULL,
    favorite BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT bookmarks_type_check CHECK (type IN ('link', 'text', 'image', 'audio', 'video'))
);

CREATE INDEX IF NOT EXISTS idx_bookmarks_user_id ON bookmarks (user_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_collection_id ON bookmarks (collection_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_type ON bookmarks (type);
CREATE INDEX IF NOT EXISTS idx_bookmarks_favorite ON bookmarks (favorite);
CREATE INDEX IF NOT EXISTS idx_bookmarks_search ON bookmarks USING GIN (
    to_tsvector('english', COALESCE(title, '') || ' ' || COALESCE(description, '') || ' ' || COALESCE(content, ''))
);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS idx_tags_user_id ON tags (user_id);
CREATE INDEX IF NOT EXISTS idx_tags_name ON tags (name);

CREATE TABLE IF NOT EXISTS bookmark_tags (
    bookmark_id BIGINT NOT NULL REFERENCES bookmarks(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (bookmark_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_bookmark_tags_bookmark_id ON bookmark_tags (bookmark_id);
CREATE INDEX IF NOT EXISTS idx_bookmark_tags_tag_id ON bookmark_tags (tag_id);

CREATE TABLE IF NOT EXISTS bookmark_canvas_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bookmark_id BIGINT NOT NULL REFERENCES bookmarks(id) ON DELETE CASCADE,
    collection_id BIGINT NULL REFERENCES collections(id) ON DELETE CASCADE,
    x_position NUMERIC(10, 2) NOT NULL DEFAULT 0,
    y_position NUMERIC(10, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (bookmark_id, collection_id)
);

CREATE INDEX IF NOT EXISTS idx_canvas_positions_bookmark_id ON bookmark_canvas_positions (bookmark_id);
CREATE INDEX IF NOT EXISTS idx_canvas_positions_collection_id ON bookmark_canvas_positions (collection_id);

CREATE TABLE IF NOT EXISTS bookmark_canvas_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_bookmark_id BIGINT NOT NULL REFERENCES bookmarks(id) ON DELETE CASCADE,
    to_bookmark_id BIGINT NOT NULL REFERENCES bookmarks(id) ON DELETE CASCADE,
    collection_id BIGINT NULL REFERENCES collections(id) ON DELETE CASCADE,
    label VARCHAR(255) NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_canvas_connections_from ON bookmark_canvas_connections (from_bookmark_id);
CREATE INDEX IF NOT EXISTS idx_canvas_connections_to ON bookmark_canvas_connections (to_bookmark_id);
CREATE INDEX IF NOT EXISTS idx_canvas_connections_collection_id ON bookmark_canvas_connections (collection_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_users_updated_at ON users;
CREATE TRIGGER set_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_collections_updated_at ON collections;
CREATE TRIGGER set_collections_updated_at
BEFORE UPDATE ON collections
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_bookmarks_updated_at ON bookmarks;
CREATE TRIGGER set_bookmarks_updated_at
BEFORE UPDATE ON bookmarks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_canvas_positions_updated_at ON bookmark_canvas_positions;
CREATE TRIGGER set_canvas_positions_updated_at
BEFORE UPDATE ON bookmark_canvas_positions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_canvas_connections_updated_at ON bookmark_canvas_connections;
CREATE TRIGGER set_canvas_connections_updated_at
BEFORE UPDATE ON bookmark_canvas_connections
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

